version: '3.1'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mysql
    volumes:
      - wordpress:/var/www/html
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: randompassword
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 10080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    volumes:
      - ./phpmyadmin/sessions:/sessions
  # php:
  #   build: ./phpmyadmin
  #   volumes:
  #     - ./php/src:/var/www/html
  #   container_name: php
  #   tty: true
volumes:
  wordpress:
  mysql:
